# Site Settings
theme                    : "minimal-mistakes-jekyll"
minimal_mistakes_skin    : "stealth"

locale                   : "en-US"
title                    : "Keshawn White"
title_separator          : "-"
name                     : "Keshawn White"
description              : "Keshawn White - Cybersecurity Portfolio"
url                      : # the base hostname & protocol for your site e.g. "https://yourdomain.com"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : # GitHub username/repo-name

# Site Author
author:
  name             : "Keshawn White"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "CISSP | CISM | Security Engineering | Compliance & Risk"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:keshawnwhite38@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/keshawn-white/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url: "https://github.com/"

# Site Footer
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/keshawn-white/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url:

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-include-cache

# Collections
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
